### ISSUE TITLE
Did you have the source code of this paper?

### ISSUE THREAD

**Issue by youweixiansheng** [hezw2016/1D-GF#1]
Thanks for you upload the code for research

**Comment by hezw2016** [comment]
This code is re-implemented by myself and validated by Dr. Cao (my advisor). I will upload ASAP.

**Comment by youweixiansheng** [comment]
thanks, could I have a copy of your code?
email: erfect@whu.edu.cn

**Comment by hezw2016** [comment]
@youweixiansheng FYI, the code has been uploaded.
